[package]
name = "standalone-tensor"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Example: standalone-tensor"

[dependencies]

[[bin]]
name = "standalone-tensor"
path = "src/main.rs"
