[package]
name = "text-classifier"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Example: text-classifier"

[dependencies]

[[bin]]
name = "text-classifier"
path = "src/main.rs"
